package movieappshkolo.com.database;


import androidx.room.Dao;

import androidx.room.Delete;

import androidx.room.Insert;

import androidx.room.OnConflictStrategy;

import androidx.room.Query;

import java.util.List;

import movieappshkolo.com.datamodel.Movie;

@Dao
public interface MovieDao {

    //WE NEED A METHOD FOR INSERTING A NEW NOTE.
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    void insertNote(Movie noteEntity);
    //NOW WE CAN USE THIS METHOD TO INSERT OR UPDATE A NOTE.ALL THE SQL CODE WILL BE GENERATED BY THE ROOM LIBRARY.

    //WE NEED A METHOD FOR INSERTING A LIST OF NOTES.
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    void insertAll(List<Movie> movies);

    //WE NEED A METHOD FOR DELETING A SINGLE NOTE
    @Delete
    void deleteNote(Movie movie);


    //NOW WE NEED QUERIES.
    //THE FIRST ONE WILL RETRIEVE A NOTE BASED ON ITS ID
    @Query("SELECT * FROM movies WHERE id = :id")
    Movie getNoteById(int id);

    //NOW WE NEED QUERY THAT RETURNS ALL OF OUR DATA
    @Query("SELECT * FROM movies")
    List<Movie> getAllMovies();

    //WE NEED A METHOD FOR DELETING ALL NOTES
    @Query("DELETE FROM movies")
    int deleteAllMovies();

    //WE NEED A METHOD FOR RETURNING THE NUMBER OF ITEMS IN THE TABLE
    @Query("SELECT COUNT(*) FROM movies")
    int getCount();

}
